# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04          # or ubuntu-20.04
  image: latest             # latest RTD build image

python:
  install:
    # 1) install your package so autodoc can import it
    - method: pip
      path: .
    # 2) install all docs-specific dependencies
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  source-directory: docs
  builder: html
