# .readthedocs.yaml
version: 2

# Which Python version to use
python:
  version: "3.10"
  install:
    # 1) Install your project in editable mode (so autodoc can import it)
    - method: pip
      path: .
    # 2) Install docs‑specific requirements
    - requirements: docs/requirements.txt

# Use the latest RTD build image
build:
  image: latest

# Sphinx builder settings
sphinx:
  builder: html
  configuration: docs/conf.py
  source-directory: docs
